# This is a better version of the FizzBuzz problem.
# It checks each integer individually (3, 5, and I).
# it uses string concatination to get results.

def FizzBuzz(n):
  # Empty list to add result
  res = []
  # For loop.
  for i in range(1, n + 1):
    # Empty string
    s = ""
    # Check number 3 remainder. 
    if i % 3 == 0: 
      s += "Fizz" # concatinate to s
    # Check number 5 remainder
    if i % 5 == 0:
      s += "Buzz"  # concatinate to s
    # if Neither, simple concatenate the number as string.
    if not s:
      s += str(i) # convert to string.
    # Push back on the list. 
    res.append(s)

  # Return list.
  return res

# Main entry.
if __name__ == '__main__':
  n = 20    # Set number to 20.
  res = FizzBuzz(n) # Get the result from the function.

  # Loop through the list generated by FizzBuzz
  for s in res:
    # Print the result.
    print(s, end=" ")

